### ISSUE TITLE
ckpt missing 

### ISSUE THREAD

**Issue by weizhou1991** [llmbev/talk2bev#4]
Hi there, 

Thank you so much for ur wonderful work, however, when I was tring to generate the base throught ur "generate_base.py" file, I found that it needs a 'last.ckpt' file. I noticed that file was used in stp3, I am curious how could I have that ckpt file and what is stp3? Is it designed by yourself or based on anything else? I really appreciate for ur help!

Best,

**Comment by Vikr-182** [comment]
Hi!
The ST-P3 model refers to this work: https://github.com/OpenDriveLab/ST-P3
The last.ckpt refers to the weights they have released in their paper, please find the link: https://drive.google.com/file/d/1fPAzrgohTVeFfyXSUh5wUHB_US8v9HFa/view

Do let me know if any help is needed!
